<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.11.1deb2+deb7u1 setup script
 * Date: Wed, 12 Nov 2014 22:58:11 +0100
 */


// Load secret generated on postinst
include('/var/lib/phpmyadmin/blowfish_secret.inc.php');

// Load autoconf local config
include('/var/lib/phpmyadmin/config.inc.php');


/* Servers configuration */
$i = 0;

/* Server: Artemis-Linux [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Artemis-Linux';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* Server: Ares - Windows 2008 - ARMAIII [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Ares - Windows 2008 - ARMAIII';
$cfg['Servers'][$i]['host'] = 'xxx.xxx.xxx.xxx';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['DefaultLang'] = 'fr';
$cfg['blowfish_secret'] = 'xxxxxxxxxxxxxxxxxxxxxxx';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['Error_Handler']['display'] = true;
$cfg['ServerDefault'] = 0;
$cfg['DisplayServersList'] = true;
$cfg['ShowPhpInfo'] = true;
?>
