#! /bin/sh
### BEGIN INIT INFO
# Provides: firewall
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Firewall initscript
# Description: This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Vider les tables actuelles
iptables -t filter -F

# Vider les règles personnelles
iptables -t filter -X

# Interdire toute connexion entrante et sortante
iptables -t filter -P INPUT DROP
iptables -t filter -P FORWARD DROP
iptables -t filter -P OUTPUT ACCEPT

# --- Ne pas casser les connexions etablies
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

# Autoriser loopback
iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A OUTPUT -o lo -j ACCEPT

# ICMP (Ping)
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT

# --- SSH In
iptables -t filter -A INPUT -p tcp --dport 87 -j ACCEPT

# SSH Out
iptables -t filter -A OUTPUT -p tcp --dport 87 -j ACCEPT

# DNS In/Out
iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT

# NTP Out
iptables -t filter -A OUTPUT -p udp --dport 123 -j ACCEPT

# HTTP + HTTPS Out
iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

# HTTP + HTTPS In
iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 8443 -j ACCEPT

# FTP Out
iptables -t filter -A OUTPUT -p tcp --dport 20:21 -j ACCEPT

# FtpS Out-In
iptables -t filter -A OUTPUT -p tcp --dport 900 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 900 -j ACCEPT

# FTP In
modprobe ip_conntrack_ftp # ligne facultative avec les serveurs OVH
iptables -t filter -A INPUT -p tcp --dport 20:21 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 60000:60500 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 60000:60500 -j ACCEPT
iptables -t filter -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Mail SMTP:25
iptables -t filter -A INPUT -p tcp --dport 25 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 25 -j ACCEPT

#Teamspeak3
iptables -t filter -A INPUT -p tcp --dport 30033 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 10011 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 2008 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 10156 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 30033 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 2008 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 10011 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 10156 -j ACCEPT

# Monit
iptables -t filter -A INPUT -p tcp --dport 1337 -j ACCEPT

#Bans
iptables -I INPUT -s 173.45.74.224/29 -j DROP
iptables -I INPUT -s 207.195.64.2/32 -j DROP
iptables -I INPUT -s 69.10.192.0/19 -j DROP
iptables -I INPUT -s 217.15.16.0/20 -j DROP
iptables -I INPUT -s 194.2.0.0/15 -j DROP
iptables -I INPUT -s 125.76.233.77/32 -j DROP
iptables -I INPUT -s 5.79.65.105 -j DROP
iptables -I INPUT -s 81.64.139.0/24 -j DROP
iptables -I INPUT -s 88.177.29.126 -j DROP
iptables -I INPUT -s 142.162.244.215 -j DROP
iptables -I INPUT -s 103.1.115.221 -j DROP


#Autor
iptables -I INPUT -s 88.190.254.18 -j ACCEPT
iptables -I INPUT -s 88.190.254.4 -j ACCEPT
iptables -I INPUT -s 88.190.254.25 -j ACCEPT
iptables -I INPUT -s 88.191.254.6 -j ACCEPT
iptables -I INPUT -s 88.191.254.7 -j ACCEPT

# Anti-Dos Syn-UDP-ICMP

iptables -A FORWARD -p tcp --syn -m limit --limit 2/second -j ACCEPT
iptables -A FORWARD -p udp -m limit --limit 2/second -j ACCEPT
iptables -A FORWARD -p icmp --icmp-type echo-request -m limit --limit 1/second -j ACCEPT

#Anti-Scan de ports

iptables -A FORWARD -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s -j ACCEPT
portsentry -atcp
portsentry -audp
